
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author karol
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new forSm Calculadora
     */
    public Calculadora() {
        initComponents();
        setLocationRelativeTo(null);
    }

    UtilsCalc utils = new UtilsCalc();
    double valor1, valor2, porcentagem;
    char sinal;

    /**
     *
     * @param caracter variavel referente aos numeros dos botões, adicionando -
     * os na tela principal, com o metodo
     *
     */
    private void adicionaStringTela(String caracter) {
        jtfTela.setText(jtfTela.getText() + caracter);
    }

    /**
     * metodo para inserir o conteudo da tela principal e o sinal da operação
     * escolhido, na tela auxiliar
     */
    private void adicionaStringTelaAux() {
        jtfTelaAuxiliar.setText(jtfTela.getText() + " " + sinal);
    }

    /**
     * metodo para calcular as operações com porcentagem
     */
    private void calculaPorcentagem() {
        switch (sinal) {
            case '+':

                jtfTela.setText(String.valueOf(utils.somarPorcentagem(valor1, valor2)));
                jtfTelaAuxiliar.setText(utils.limpaTela());
                break;

            case '-':

                jtfTela.setText(String.valueOf(utils.subtrairPorcentagem(valor1, valor2)));
                jtfTelaAuxiliar.setText(utils.limpaTela());
                break;

            case 'X':

                jtfTela.setText(String.valueOf(utils.multiplicarPorcentagem(valor1, valor2)));
                jtfTelaAuxiliar.setText(utils.limpaTela());
                break;

            case '÷':

                jtfTela.setText(String.valueOf(utils.dividirPorcentagem(valor1, valor2)));
                jtfTelaAuxiliar.setText(utils.limpaTela());
                break;

            default:
                utils.limpaTela();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jtfTela = new javax.swing.JTextField();
        jtfTelaAuxiliar = new javax.swing.JTextField();
        jbtnApagaTudo = new javax.swing.JButton();
        jbtnApagaUmCaracter = new javax.swing.JButton();
        jbtnRaiz = new javax.swing.JButton();
        jbtnDividir = new javax.swing.JButton();
        jbtnSete = new javax.swing.JButton();
        jbtnOito = new javax.swing.JButton();
        jbtnNove = new javax.swing.JButton();
        jbtnMultiplicar = new javax.swing.JButton();
        jbtnQuatro = new javax.swing.JButton();
        jbtnCinco = new javax.swing.JButton();
        jbtnSeis = new javax.swing.JButton();
        jbtnSubtrair = new javax.swing.JButton();
        jbtnUm = new javax.swing.JButton();
        jbtnDois = new javax.swing.JButton();
        jbtnTres = new javax.swing.JButton();
        jbtnSomar = new javax.swing.JButton();
        jbtnZero = new javax.swing.JButton();
        jbtnPonto = new javax.swing.JButton();
        jbtnIgual = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jbtnPorcentagem = new javax.swing.JButton();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(52, 52, 52));
        jPanel1.setRequestFocusEnabled(false);

        jtfTela.setEditable(false);
        jtfTela.setBackground(new java.awt.Color(117, 117, 117));
        jtfTela.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtfTela.setForeground(new java.awt.Color(255, 255, 255));
        jtfTela.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfTela.setToolTipText("");
        jtfTela.setFocusable(false);
        jtfTela.setRequestFocusEnabled(false);

        jtfTelaAuxiliar.setEditable(false);
        jtfTelaAuxiliar.setBackground(new java.awt.Color(117, 117, 117));
        jtfTelaAuxiliar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jtfTelaAuxiliar.setForeground(new java.awt.Color(255, 255, 255));
        jtfTelaAuxiliar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfTelaAuxiliar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtfTelaAuxiliar.setFocusable(false);

        jbtnApagaTudo.setBackground(new java.awt.Color(66, 65, 65));
        jbtnApagaTudo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnApagaTudo.setForeground(new java.awt.Color(255, 255, 255));
        jbtnApagaTudo.setText("C");
        jbtnApagaTudo.setToolTipText("apagar");
        jbtnApagaTudo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnApagaTudo.setFocusable(false);
        jbtnApagaTudo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnApagaTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnApagaTudoActionPerformed(evt);
            }
        });

        jbtnApagaUmCaracter.setBackground(new java.awt.Color(66, 65, 65));
        jbtnApagaUmCaracter.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnApagaUmCaracter.setForeground(new java.awt.Color(255, 255, 255));
        jbtnApagaUmCaracter.setText("CE");
        jbtnApagaUmCaracter.setToolTipText("apagar");
        jbtnApagaUmCaracter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnApagaUmCaracter.setFocusable(false);
        jbtnApagaUmCaracter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnApagaUmCaracter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnApagaUmCaracterActionPerformed(evt);
            }
        });

        jbtnRaiz.setBackground(new java.awt.Color(66, 65, 65));
        jbtnRaiz.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnRaiz.setForeground(new java.awt.Color(255, 255, 255));
        jbtnRaiz.setText("√");
        jbtnRaiz.setToolTipText("raíz quadrada");
        jbtnRaiz.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnRaiz.setFocusable(false);
        jbtnRaiz.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRaizActionPerformed(evt);
            }
        });

        jbtnDividir.setBackground(new java.awt.Color(66, 65, 65));
        jbtnDividir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnDividir.setForeground(new java.awt.Color(255, 255, 255));
        jbtnDividir.setText("÷");
        jbtnDividir.setToolTipText("dividir");
        jbtnDividir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnDividir.setFocusable(false);
        jbtnDividir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDividirActionPerformed(evt);
            }
        });

        jbtnSete.setBackground(new java.awt.Color(66, 65, 65));
        jbtnSete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnSete.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSete.setText("7");
        jbtnSete.setToolTipText("sete");
        jbtnSete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnSete.setFocusable(false);
        jbtnSete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnSete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSeteActionPerformed(evt);
            }
        });

        jbtnOito.setBackground(new java.awt.Color(66, 65, 65));
        jbtnOito.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnOito.setForeground(new java.awt.Color(255, 255, 255));
        jbtnOito.setText("8");
        jbtnOito.setToolTipText("oito");
        jbtnOito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnOito.setFocusable(false);
        jbtnOito.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnOito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOitoActionPerformed(evt);
            }
        });

        jbtnNove.setBackground(new java.awt.Color(66, 65, 65));
        jbtnNove.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnNove.setForeground(new java.awt.Color(255, 255, 255));
        jbtnNove.setText("9");
        jbtnNove.setToolTipText("nove");
        jbtnNove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnNove.setFocusable(false);
        jbtnNove.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnNove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNoveActionPerformed(evt);
            }
        });

        jbtnMultiplicar.setBackground(new java.awt.Color(66, 65, 65));
        jbtnMultiplicar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnMultiplicar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnMultiplicar.setText("X");
        jbtnMultiplicar.setToolTipText("multiplicar");
        jbtnMultiplicar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnMultiplicar.setFocusable(false);
        jbtnMultiplicar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMultiplicarActionPerformed(evt);
            }
        });

        jbtnQuatro.setBackground(new java.awt.Color(66, 65, 65));
        jbtnQuatro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnQuatro.setForeground(new java.awt.Color(255, 255, 255));
        jbtnQuatro.setText("4");
        jbtnQuatro.setToolTipText("quatro");
        jbtnQuatro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnQuatro.setFocusable(false);
        jbtnQuatro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnQuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnQuatroActionPerformed(evt);
            }
        });

        jbtnCinco.setBackground(new java.awt.Color(66, 65, 65));
        jbtnCinco.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnCinco.setForeground(new java.awt.Color(255, 255, 255));
        jbtnCinco.setText("5");
        jbtnCinco.setToolTipText("cinco");
        jbtnCinco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnCinco.setFocusable(false);
        jbtnCinco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCincoActionPerformed(evt);
            }
        });

        jbtnSeis.setBackground(new java.awt.Color(66, 65, 65));
        jbtnSeis.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnSeis.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSeis.setText("6");
        jbtnSeis.setToolTipText("seis");
        jbtnSeis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnSeis.setFocusable(false);
        jbtnSeis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSeisActionPerformed(evt);
            }
        });

        jbtnSubtrair.setBackground(new java.awt.Color(66, 65, 65));
        jbtnSubtrair.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnSubtrair.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSubtrair.setText("-");
        jbtnSubtrair.setToolTipText("subtrair");
        jbtnSubtrair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnSubtrair.setFocusable(false);
        jbtnSubtrair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnSubtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSubtrairActionPerformed(evt);
            }
        });

        jbtnUm.setBackground(new java.awt.Color(66, 65, 65));
        jbtnUm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnUm.setForeground(new java.awt.Color(255, 255, 255));
        jbtnUm.setText("1");
        jbtnUm.setToolTipText("um");
        jbtnUm.setActionCommand("");
        jbtnUm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnUm.setFocusable(false);
        jbtnUm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUmActionPerformed(evt);
            }
        });

        jbtnDois.setBackground(new java.awt.Color(66, 65, 65));
        jbtnDois.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnDois.setForeground(new java.awt.Color(255, 255, 255));
        jbtnDois.setText("2");
        jbtnDois.setToolTipText("dois");
        jbtnDois.setActionCommand("");
        jbtnDois.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnDois.setFocusable(false);
        jbtnDois.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDoisActionPerformed(evt);
            }
        });

        jbtnTres.setBackground(new java.awt.Color(66, 65, 65));
        jbtnTres.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnTres.setForeground(new java.awt.Color(255, 255, 255));
        jbtnTres.setText("3");
        jbtnTres.setToolTipText("três");
        jbtnTres.setActionCommand("");
        jbtnTres.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnTres.setFocusable(false);
        jbtnTres.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTresActionPerformed(evt);
            }
        });

        jbtnSomar.setBackground(new java.awt.Color(66, 65, 65));
        jbtnSomar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnSomar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSomar.setText("+");
        jbtnSomar.setToolTipText("somar");
        jbtnSomar.setActionCommand("");
        jbtnSomar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnSomar.setFocusable(false);
        jbtnSomar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnSomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSomarActionPerformed(evt);
            }
        });

        jbtnZero.setBackground(new java.awt.Color(66, 65, 65));
        jbtnZero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnZero.setForeground(new java.awt.Color(255, 255, 255));
        jbtnZero.setText("0");
        jbtnZero.setToolTipText("zero");
        jbtnZero.setActionCommand("");
        jbtnZero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnZero.setFocusable(false);
        jbtnZero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnZeroActionPerformed(evt);
            }
        });

        jbtnPonto.setBackground(new java.awt.Color(66, 65, 65));
        jbtnPonto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnPonto.setForeground(new java.awt.Color(255, 255, 255));
        jbtnPonto.setText(".");
        jbtnPonto.setToolTipText("ponto");
        jbtnPonto.setActionCommand("");
        jbtnPonto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnPonto.setFocusable(false);
        jbtnPonto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnPonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPontoActionPerformed(evt);
            }
        });

        jbtnIgual.setBackground(new java.awt.Color(66, 65, 65));
        jbtnIgual.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnIgual.setForeground(new java.awt.Color(255, 255, 255));
        jbtnIgual.setText("=");
        jbtnIgual.setToolTipText("igual");
        jbtnIgual.setActionCommand("");
        jbtnIgual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnIgual.setFocusable(false);
        jbtnIgual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIgualActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CALCULADORA");
        jLabel1.setFocusable(false);

        jbtnPorcentagem.setBackground(new java.awt.Color(66, 65, 65));
        jbtnPorcentagem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnPorcentagem.setForeground(new java.awt.Color(255, 255, 255));
        jbtnPorcentagem.setText("%");
        jbtnPorcentagem.setToolTipText("porcentagem");
        jbtnPorcentagem.setActionCommand("");
        jbtnPorcentagem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnPorcentagem.setFocusable(false);
        jbtnPorcentagem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnPorcentagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPorcentagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jtfTela)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtnSete, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnApagaTudo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnUm, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbtnApagaUmCaracter, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnPorcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbtnOito, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnNove, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbtnCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jbtnDois, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbtnTres, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jbtnPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbtnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtnSomar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnSubtrair, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jtfTelaAuxiliar))
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfTelaAuxiliar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfTela, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnApagaUmCaracter, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnApagaTudo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPorcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnOito, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnNove, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnUm, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnDois, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnTres, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSubtrair, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtnSomar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnZeroActionPerformed
        // adiciona numero 0
        adicionaStringTela("0");

    }//GEN-LAST:event_jbtnZeroActionPerformed

    private void jbtnUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUmActionPerformed
        // adiciona numero 1

        adicionaStringTela("1");
    }//GEN-LAST:event_jbtnUmActionPerformed

    private void jbtnDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDoisActionPerformed
        // adiciona numero 2

        adicionaStringTela("2");
    }//GEN-LAST:event_jbtnDoisActionPerformed

    private void jbtnTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTresActionPerformed
        // adiciona numero 3

        adicionaStringTela("3");
    }//GEN-LAST:event_jbtnTresActionPerformed

    private void jbtnQuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnQuatroActionPerformed
        // adiciona numero 4

        adicionaStringTela("4");
    }//GEN-LAST:event_jbtnQuatroActionPerformed

    private void jbtnCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCincoActionPerformed
        // adiciona numero 5

        adicionaStringTela("5");
    }//GEN-LAST:event_jbtnCincoActionPerformed

    private void jbtnSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSeisActionPerformed
        // adiciona numero 6

        adicionaStringTela("6");
    }//GEN-LAST:event_jbtnSeisActionPerformed

    private void jbtnSeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSeteActionPerformed
        // adiciona numero 7

        adicionaStringTela("7");
    }//GEN-LAST:event_jbtnSeteActionPerformed

    private void jbtnOitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOitoActionPerformed
        //adiciona numero 8

        adicionaStringTela("8");

    }//GEN-LAST:event_jbtnOitoActionPerformed

    private void jbtnNoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNoveActionPerformed
        // adiciona numero 9

        adicionaStringTela("9");
    }//GEN-LAST:event_jbtnNoveActionPerformed

    private void jbtnPontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPontoActionPerformed
        // adiciona o ponto/virgula

        if (jtfTela.getText().isEmpty()) {
            adicionaStringTela("0.");
        }
        if (!jtfTela.getText().contains(".")) {
            adicionaStringTela(".");
        }


    }//GEN-LAST:event_jbtnPontoActionPerformed

    private void jbtnApagaTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnApagaTudoActionPerformed
        // apaga todos os caracteres da tela principal e tela auxiliar

        jtfTela.setText(utils.limpaTela());
        jtfTelaAuxiliar.setText(utils.limpaTela());
    }//GEN-LAST:event_jbtnApagaTudoActionPerformed

    private void jbtnApagaUmCaracterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnApagaUmCaracterActionPerformed
        // apaga um caracter de cada vez na tela principal

        try {
            jtfTela.setText(jtfTela.getText().substring(0, jtfTela.getText().length() - 1));

        } catch (Exception e) {
            jtfTela.setText("");
        }
    }//GEN-LAST:event_jbtnApagaUmCaracterActionPerformed

    private void jbtnSomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSomarActionPerformed
        // botão somar

        if (jtfTela.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Insira algum número para realizar a operação", "Informação", JOptionPane.ERROR_MESSAGE);

        } else {
            valor1 = Double.parseDouble(jtfTela.getText());
            sinal = '+';
            adicionaStringTelaAux();
            jtfTela.setText(utils.limpaTela());
        }
    }//GEN-LAST:event_jbtnSomarActionPerformed

    private void jbtnSubtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSubtrairActionPerformed
        // botão subtrair

        if (jtfTela.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Insira algum número para realizar a operação", "Informação", JOptionPane.ERROR_MESSAGE);
        } else {
            valor1 = Double.parseDouble(jtfTela.getText());
            sinal = '-';
            adicionaStringTelaAux();
            jtfTela.setText(utils.limpaTela());
        }
    }//GEN-LAST:event_jbtnSubtrairActionPerformed

    private void jbtnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMultiplicarActionPerformed
        // botão multiplicar

        if (jtfTela.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Insira algum número para realizar a operação", "Informação", JOptionPane.ERROR_MESSAGE);
        } else {
            valor1 = Double.parseDouble(jtfTela.getText());
            sinal = 'X';
            adicionaStringTelaAux();
            jtfTela.setText(utils.limpaTela());
        }
    }//GEN-LAST:event_jbtnMultiplicarActionPerformed

    private void jbtnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDividirActionPerformed
        // botão dividir

        if (jtfTela.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Insira algum número para realizar a operação", "Informação", JOptionPane.ERROR_MESSAGE);
        } else {
            valor1 = Double.parseDouble(jtfTela.getText());
            sinal = '÷';
            adicionaStringTelaAux();
            jtfTela.setText(utils.limpaTela());
        }
    }//GEN-LAST:event_jbtnDividirActionPerformed

    private void jbtnRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRaizActionPerformed
        // botão raíz quadrada

        if (jtfTela.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Insira algum número para realizar a operação", "Informação", JOptionPane.ERROR_MESSAGE);
        } else {
            valor1 = Double.parseDouble(jtfTela.getText());
            sinal = '√';
            adicionaStringTelaAux();
        }
    }//GEN-LAST:event_jbtnRaizActionPerformed

    private void jbtnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIgualActionPerformed
        // botão igual

        if (jtfTela.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Insira algum número para realizar a operação", "Informação", JOptionPane.ERROR_MESSAGE);
        } else {
            valor2 = Double.parseDouble(jtfTela.getText());

            switch (sinal) {
                case '+':
                    jtfTela.setText(String.valueOf(utils.somar(valor1, valor2)));
                    jtfTelaAuxiliar.setText(utils.limpaTela());
                    break;

                case '-':
                    jtfTela.setText(String.valueOf(utils.subtrair(valor1, valor2)));
                    jtfTelaAuxiliar.setText(utils.limpaTela());
                    break;

                case 'X':
                    jtfTela.setText(String.valueOf(utils.multiplicar(valor1, valor2)));
                    jtfTelaAuxiliar.setText(utils.limpaTela());
                    break;

                case '÷':
                    jtfTela.setText(String.valueOf(utils.dividir(valor1, valor2)));
                    jtfTelaAuxiliar.setText(utils.limpaTela());
                    break;

                case '√':
                    jtfTela.setText(String.valueOf(utils.raiz(valor1)));
                    jtfTelaAuxiliar.setText(utils.limpaTela());
                    break;

                default:
                    utils.limpaTela();

            }
        }

    }//GEN-LAST:event_jbtnIgualActionPerformed

    private void jbtnPorcentagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPorcentagemActionPerformed
        // botão porcentagem
        if (jtfTela.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Insira algum número para realizar a operação", "Informação", JOptionPane.ERROR_MESSAGE);
        } else if (!jtfTelaAuxiliar.getText().isEmpty()) {
            valor2 = Double.parseDouble(jtfTela.getText());
            calculaPorcentagem();
        }
    }//GEN-LAST:event_jbtnPorcentagemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnApagaTudo;
    private javax.swing.JButton jbtnApagaUmCaracter;
    private javax.swing.JButton jbtnCinco;
    private javax.swing.JButton jbtnDividir;
    private javax.swing.JButton jbtnDois;
    private javax.swing.JButton jbtnIgual;
    private javax.swing.JButton jbtnMultiplicar;
    private javax.swing.JButton jbtnNove;
    private javax.swing.JButton jbtnOito;
    private javax.swing.JButton jbtnPonto;
    private javax.swing.JButton jbtnPorcentagem;
    private javax.swing.JButton jbtnQuatro;
    private javax.swing.JButton jbtnRaiz;
    private javax.swing.JButton jbtnSeis;
    private javax.swing.JButton jbtnSete;
    private javax.swing.JButton jbtnSomar;
    private javax.swing.JButton jbtnSubtrair;
    private javax.swing.JButton jbtnTres;
    private javax.swing.JButton jbtnUm;
    private javax.swing.JButton jbtnZero;
    private javax.swing.JTextField jtfTela;
    private javax.swing.JTextField jtfTelaAuxiliar;
    // End of variables declaration//GEN-END:variables

}
